theme: minima
title: JavaScript.js
author: restStateTransfer
email: private
description: 
  JavaScript is great. 
  
# social links
twitter_username: never heard of it;
github_username:  restStateTransfer

show_excerpts: false
